apiVersion: v1
kind: Service
metadata:
  name: my-plain-backend-service
spec:
  type: ClusterIP
  selector:
    app: interest
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080