apiVersion: v1
kind: Service
metadata:
  name: my-plain-frontend-service
spec:
  type: ClusterIP
  selector:
    app: loan
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080