apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# declare ConfigMap as a resource
resources:
- backend-active.yml
- frontend-active.yml
- backend-preview.yml
- frontend-preview.yml
- rollout-fe.yml
- rollout-be.yml

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml


# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: my-frontend-settings
  literals: 
  - APP_VERSION=1.0 # If updating the app version, update BACKEND_HOST at the same time
  - BACKEND_HOST="backend-active" # When previewing this should be set to `backend-preview` and afterwards reset to `backend-active`